const SLACK_DEFAULT_CHANNEL = process.env.SLACK_DEFAULT_CHANNEL;
const SLACK_DEFAULT_TOKEN = process.env.SLACK_DEFAULT_TOKEN;
const SLACK_RESPONSE_URL = process.env.SLACK_RESPONSE_URL;
const SLACK_WORKSPACE = process.env.SLACK_WORKSPACE;

export {
  SLACK_DEFAULT_CHANNEL,
  SLACK_DEFAULT_TOKEN,
  SLACK_RESPONSE_URL,
  SLACK_WORKSPACE
};
